### PR TITLE
feat: check PRs type

### PR DESCRIPTION
**Pull request by HarunamiYaki**
## Changes
check PRs type is "User" or "Bot", give a different statement for each value
```ts
switch (payload) {
    case value:
        break;
    default:
        break;
}
```

### CODE REVIEW

**Comment by HarunamiYaki** [comment]
some lines are not given semicolons, should I add additional rules in eslint? @Muunatic

**Comment by Muunatic** [comment]
there are several rules that I want to add later, so no need to add additional rules for now

**Comment by HarunamiYaki** [comment]
Ready for review @Muunatic

**Review by Muunatic — APPROVED** [review]
LGTM!

**Comment by HarunamiYaki** [comment]
Ready to merge

**Pull request merged**
